### ISSUE TITLE
Dataloader for Tau simulation files

### ISSUE THREAD

**Issue by AndreWeiner** [AndreWeiner/flowtorch#12]
- dataloader to load simulation results produced by the Tau code; each snapshot has to be saved in a single file

**Comment by AndreWeiner** [comment]
Hi @MehdiMak96,

TAU writes [netCDF4](https://unidata.github.io/netcdf4-python/) files. You can install the netCDF4 library with pip:
```
pip3 install netCDF4
```
To create a Dataloader, the following information must be extracted from the test files you will receive:

- [ ] find all relevant simulation files (solution and mesh) in a location provided by the user (tip: use *glob*)
- [ ] extract the time value from each file name; at the end, there should be a list with the time values as strings, e.g., `["1.0e-3", "2.0e-3", ...]`
- [ ] the available fields as a list of strings, e.g., `["x_velocity", "density", "pressure", ...]`; this list should not contain the vertices of cell volumes
- [ ] the vertices as a PyTorch tensor of shape *n_points x 3*, where each column holds the x/y/z values; you can convert the arrays via NumPy; netCDF4 can convert to NumPy and PyTorch can create tensors from NumPy arrays
- [ ] the cell volumes as PyTorch tensor
- [ ] the values of any field as PyTorch tensor

Here is some starter code to explore a TAU simulation file:
```
from netCDF4 import Dataset

file_path = "/path/to/tau_backward_facing_step/"
grid_path = file_path + "PW_DES-HybQuadTRex-v2_yp-50_s1.15_ny67.grd"
data_path = file_path + "sol.pval.unsteady_i=14790_t=2.9580000000e-02"

grid = Dataset(grid_path)
data = Dataset(data_path)
print("Variables in grid file:")
for key in grid.variables.keys():
    print(key, grid.variables[key].shape, grid.variables[key].dtype)
print("-"*80)

print("Variables in data file:")
for key in data.variables.keys():
    print(key, data[key].shape)
print("-"*80)
```
You can solve the task outside of the *flowTorch* repository and post your solution here.

Best, Andre

**Comment by MehdiMak96** [comment]
Hallo Andre,

I'm at the point now where I have to create an array via Numpy but I'm a bit confused cause all the values are the same (1119348) ,am I doing something wrong? Or should I continue?

Best, Mehdi

**Comment by AndreWeiner** [comment]
The value in parenthesis indicates the size of the dataset. So, for a given mesh, it makes sense that all fields have the same size. To access the field values, you do something like
```
field = dataset["field_name"][:]
```
Best, Andre

**Comment by AndreWeiner** [comment]
Hi Mehdi,
thanks for your efforts!
Best, Andre
