### ISSUE TITLE
Test flowTorch wheel package

### ISSUE THREAD

**Issue by AndreWeiner** [AndreWeiner/flowtorch#17]
Dear @MehdiMak96 and @Tushargh29,

please have a look if the following flowTorch package installation works for you.

1. download this [wheel package](https://cloudstorage.tu-braunschweig.de/getlink/fiTjFqvw1QshfW2ircM4VFUk/flowTorch-0.1-py3-none-any.whl)
2. open a terminal and navigate to the folder in which the *.whl* file is located
3. run `pip install flowTorch-0.1-py3-none-any.whl`
4. running `pip list | grep flowTorch` should now display something like `flowTorch 0.1`
5. start python3 by typing `python3` in the terminal; then run
```
>> import flowtorch
>> flowtorch.__version__
# expected output
'0.1'
```
If the above steps work, I'll add some additional tests hereafter.

Best, Andre

**Comment by Tushargh29** [comment]
Hello sir,

It is working for me.
Thanks.

Best,
Tushar

**Comment by MehdiMak96** [comment]
Hello Andre,

It is working but just for the record I used pip3 instead.

Best ,Andre
